language: php
cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.php-cs-fixer

branches:
    except:
    - /\+travis\d+$/

php:
  - 5.6
  - 7.1
  - 7.2

addons:
    apt:
        packages:
            - moreutils
            - gettext
    # seems no effect #         - php5-common

install:
    - composer require --dev friendsofphp/php-cs-fixer
    - sudo curl -L https://raw.githubusercontent.com/smarty-gettext/smarty-gettext/master/tsmarty2c.php -o /usr/local/bin/tsmarty2c
    - sudo chmod 0755 /usr/local/bin/tsmarty2c

script:
    - vendor/bin/php-cs-fixer --no-interaction --dry-run --diff -v fix
    # Check against CRLF
    - scripts/check-crlf.sh
    # Check against trailing whitespaces on php files
    - scripts/check-trailling-spaces.sh .
    # Check against non utf-8 files
    - scripts/check-utf8.sh .
    # TODO ? phplint.sh and check-php-cs-fixer.sh

jobs:
  include:
    - stage: deploy
      php: 5.6
      script:
        - scripts/export-translations-github.sh
        - scripts/import-translations-github.sh
