
image: geokrety/unittest:latest

pipelines:
  default:
    - step:
        script:
          - pwd
          # Check against CRLF
          - scripts/check-crlf.sh
          # Check against trailing whitespaces on php files
          - scripts/check-trailling-spaces.sh .
          # Check against non utf-8 files
          - scripts/check-utf8.sh .

          # Check php syntax
          - scripts/phplint.sh .
          # Check php Coding Standard
          - scripts/check-php-cs-fixer.sh
