version: '3'

services:
    mariadb:
        image: mariadb
        ports:
            - "3306:3306"
#        volumes:
#            - ./resources/mariadb:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - TIME_ZONE=UTC